### ISSUE TITLE
Does int8 calibration DatasetCalibrator buffer support multiple inputs?

### ISSUE THREAD

**Issue by 0yueyunfei0** [grimoire/torch2trt_dynamic#17]
Hi, in the project int8 calibration part `DatasetCalibrator` has mentioned [`buffer`](https://github.com/grimoire/torch2trt_dynamic/blob/167e8f0395a7b3aa781b9a30c17c633315e4d204/torch2trt_dynamic/calibration.py#L58), can this buffer support multiple inputs as one input?

**Comment by grimoire** [comment]
Hi,
Sorry for my late reply. Did you mean that your model has multiple inputs? The `DatasetCalibrator` should support multiple inputs if you provide the right dataset. If you meet any problem with it. Please share the error log here so I can provide further help.

**Comment by 0yueyunfei0** [comment]
Thank you for your reply.
I have found that the most critical part of the `get_batch` method is to return the data [pointer](https://github.com/grimoire/torch2trt_dynamic/blob/167e8f0395a7b3aa781b9a30c17c633315e4d204/torch2trt_dynamic/calibration.py#L62) of the inputs,i took a different procedure than your `get_batch` procedure and just make sure that the **data pointers(in my case it was two) to the inputs was returned**, It seems that the calibration was successful
