### ISSUE TITLE
Warning: Encountered known unsupported method torch.Tensor.__format__

### ISSUE THREAD

**Issue by iAlexKai** [grimoire/torch2trt_dynamic#18]
--------------------------------------------------------------------------------
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
--------------------------------------------------------------------------------
I know it's an issue caused by the unrealized method.
But I really don't understand where on earth did I use the "Tensor.__format__", because I have read every single line of my model code and I didn't find any use of "{}".format(model)

Could anyone help me...Thanks so much...

My environment: 
1. NVIDIA Jetson nano
2. tensorrt 7.1.3.0

**Comment by iAlexKai** [comment]
All the warning are listed here:
Warning: Encountered known unsupported method torch.is_grad_enabled
Warning: Encountered known unsupported method torch.get_default_dtype
Warning: Encountered known unsupported method torch.get_default_dtype
Warning: Encountered known unsupported method torch.Tensor.has_names
Warning: Encountered known unsupported method torch.is_grad_enabled
Warning: Encountered known unsupported method torch.is_grad_enabled
Warning: Encountered known unsupported method torch.Tensor.__iter__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.item
Warning: Encountered known unsupported method torch.Tensor.__format__
Warning: Encountered known unsupported method torch.Tensor.tolist
Warning: Encountered known unsupported method torch.Tensor.has_names
Warning: Encountered known unsupported method torch.is_grad_enabled
Warning: Encountered known unsupported method torch.Tensor.__repr__

**Comment by iAlexKai** [comment]
I have found where such warnings come from: in xxx/site-packages/torch/tensor.py(411)__format__()
`def __format__(self, format_spec):
         if self.dim() == 0:
             return self.item().__format__(format_spec)`
But I dont't know where I use the format function...

**Comment by iAlexKai** [comment]
I've got it, the only reason is that I called print(inputs) in torch2trt_dynamic.py line 514

**Comment by grimoire** [comment]
Thanks for the report, I will add some warnings about print Tensor.
