### ISSUE TITLE
No module named 'torch2trt_dynamic.converters.identity'

### ISSUE THREAD

**Issue by xuweidongkobe** [grimoire/torch2trt_dynamic#31]
I install the 0.5.0 version, when I run the  mmdetection2trt demo ,it shows the error:No module named 'torch2trt_dynamic.converters.identity'. Can you help me,how to solve the problem, thank you

**Comment by grimoire** [comment]
Are you installed on windows? Please note that windows treat `identity.py` and `Identity.py` as the same file, one of them might be removed.

**Comment by xuweidongkobe** [comment]
@grimoire thank you for your replay , I install in linux docker.
