### ISSUE TITLE
is this library supposed to be compatible with original torch2trt library?

### ISSUE THREAD

**Issue by gengshenghong** [grimoire/torch2trt_dynamic#6]
is this library supposed to be compatible with original torch2trt library? As the library use same package name with original one, we can only install one of them. The issue is, when I use this dynamic version on Jetson Nano, the Nvidia trt_pose (who depends on torch2trt library) example (https://github.com/NVIDIA-AI-IOT/trt_pose) does not work well.

I am not very familiar with these libraries, please help to confirm if it supposed to be compatible before looking into details. If yes, I can paste the errors here. If no, it may be an issue to override the official torch2trt library and any suggestions?

Thanks,
Shenghong

**Comment by grimoire** [comment]
Hi
Thanks for the suggestion. 
That's my mistake. The time when I create this repo, it is just a fork of the official one, not an public project. And I do plan to deprecate it after the official one provide better dynamic shape support.
I will change the names ASAP.

**Comment by gengshenghong** [comment]
Thanks @grimoire for your confirmation. You may also need to update the code in your https://github.com/grimoire/mmdetection-to-tensorrt project (not sure whether other projects also reference this library), as it does not work with official torch2rt version as of now. When official one provides dynamic support, you can revert the changes. :)

**Comment by grimoire** [comment]
Hi
I have change the name from `torch2trt` to `torch2trt_dynamic`, include [mmdetection-to-tensorrt](https://github.com/grimoire/mmdetection-to-tensorrt). A lot of files has been changed.
If you found any error. Just let me know.
Thanks.

**Comment by gengshenghong** [comment]
Hi @grimoire , I've tested and it worked well to install the same library together now. I'll close this issue.

Thanks,
Shenghong
