### ISSUE TITLE
topk issue

### ISSUE THREAD

**Issue by niaoyu** [grimoire/torch2trt_dynamic#8]
Hi, I used these repo to transfer the following code from torch to trt.
```python
    topk_scores, topk_inds = torch.topk(scores.view(batch, cat, height*width), K)
    topk_inds = topk_inds.int()
    topk_inds = topk_inds % (height * width)
```

However, the error shown here.
[TensorRT] ERROR: (Unnamed Layer* 98) [TopK]: reduceAxes out of range

 Are there some issues in convert/topk.py?

**Comment by grimoire** [comment]
Hi
The code works fine on my side. Could you please provide more detail? Such as shape of score, value of K etc.

**Comment by niaoyu** [comment]
> Hi
> The code works fine on my side. Could you please provide more detail? Such as shape of score, value of K etc.

Sry, it is caused by my mistake!
Such a great work, many thanks!
