### ISSUE TITLE
Is it possible to disable dynamic_shape feature?

### ISSUE THREAD

**Issue by 111qqz** [grimoire/torch2trt_dynamic#9]
Hi,Thanks to this repo for saving me a lot of time using mmdet on nano.
The problem is that I don't want to use TensorRT [dynamic_shape feature ](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work_dynamic_shapes). I comment code below,but still get output dim like [-1,1000].
```python

        config = builder.create_builder_config()
        config.max_workspace_size = max_workspace_size
        # profile = builder.create_optimization_profile()

        # if input_names is None:
        #     input_names = ['input_%d' % i for i in range(len(inputs))]
        # for input_index, input_tensor in enumerate(inputs):
        #     if opt_shape_param is not None:
        #         min_shape = tuple(opt_shape_param[input_index][0][:])
        #         opt_shape = tuple(opt_shape_param[input_index][1][:])
        #         max_shape = tuple(opt_shape_param[input_index][2][:])
        #     else:
        #         opt_shape = tuple(input_tensor.shape)
        #         min_shape = opt_shape
        #         max_shape = opt_shape
        #     profile.set_shape(
        #         input_names[input_index], min_shape, opt_shape, max_shape)
        # config.add_optimization_profile(profile)
```
Is there any gloabl flag to control this behavior? Thanks

**Comment by grimoire** [comment]
Hi
For now, the answer is no. I make this repo as a complement of official [torch2trt](https://github.com/NVIDIA-AI-IOT/torch2trt).
If you does not need dynamic shape, the official one should be enough.
And I will add this to my TODO list. Thanks for your suggestion.

**Comment by 111qqz** [comment]
thanks for your reply.
